# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'app.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1121, 683)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        MainWindow.setFont(font)
        MainWindow.setStyleSheet("background: rgb(255, 255, 255)")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(0, 0, 1121, 51))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.frame.setFont(font)
        self.frame.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border: 1px solid black;")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.CreateButton = QtWidgets.QPushButton(self.frame)
        self.CreateButton.setGeometry(QtCore.QRect(965, 5, 151, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        self.CreateButton.setFont(font)
        self.CreateButton.setAutoFillBackground(False)
        self.CreateButton.setStyleSheet("background-color: rgb(100, 210, 255);\n"
"border: 1px solid black;")
        self.CreateButton.setObjectName("CreateButton")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(70, 10, 751, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.label.setFont(font)
        self.label.setStyleSheet("border: none;")
        self.label.setTextFormat(QtCore.Qt.AutoText)
        self.label.setObjectName("label")
        self.icon_frame = QtWidgets.QFrame(self.frame)
        self.icon_frame.setGeometry(QtCore.QRect(20, 10, 31, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.icon_frame.setFont(font)
        self.icon_frame.setStyleSheet("background-image: url(circle-star.svg.png);\n"
"border: none;")
        self.icon_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.icon_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.icon_frame.setObjectName("icon_frame")
        self.org_label = QtWidgets.QLabel(self.centralwidget)
        self.org_label.setGeometry(QtCore.QRect(40, 66, 211, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        self.org_label.setFont(font)
        self.org_label.setObjectName("org_label")
        self.org_text = QtWidgets.QTextEdit(self.centralwidget)
        self.org_text.setGeometry(QtCore.QRect(40, 90, 211, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        self.org_text.setFont(font)
        self.org_text.setStyleSheet("background: rgb(242,242,242);")
        self.org_text.setObjectName("org_text")
        self.podraz_text = QtWidgets.QTextEdit(self.centralwidget)
        self.podraz_text.setGeometry(QtCore.QRect(40, 150, 211, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        self.podraz_text.setFont(font)
        self.podraz_text.setStyleSheet("background: rgb(242,242,242);")
        self.podraz_text.setObjectName("podraz_text")
        self.podraz_label = QtWidgets.QLabel(self.centralwidget)
        self.podraz_label.setGeometry(QtCore.QRect(40, 130, 211, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        self.podraz_label.setFont(font)
        self.podraz_label.setObjectName("podraz_label")
        self.data_create_label = QtWidgets.QLabel(self.centralwidget)
        self.data_create_label.setGeometry(QtCore.QRect(330, 130, 161, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        self.data_create_label.setFont(font)
        self.data_create_label.setObjectName("data_create_label")
        self.textEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit.setGeometry(QtCore.QRect(330, 90, 161, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        self.textEdit.setFont(font)
        self.textEdit.setStyleSheet("background: rgb(242,242,242);")
        self.textEdit.setObjectName("textEdit")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(330, 70, 161, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.date_create = QtWidgets.QDateTimeEdit(self.centralwidget)
        self.date_create.setGeometry(QtCore.QRect(330, 150, 161, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        self.date_create.setFont(font)
        self.date_create.setStyleSheet("background: rgb(242,242,242);")
        self.date_create.setCalendarPopup(True)
        self.date_create.setObjectName("date_create")
        self.begin_label = QtWidgets.QLabel(self.centralwidget)
        self.begin_label.setGeometry(QtCore.QRect(560, 70, 191, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        self.begin_label.setFont(font)
        self.begin_label.setObjectName("begin_label")
        self.end_label = QtWidgets.QLabel(self.centralwidget)
        self.end_label.setGeometry(QtCore.QRect(560, 130, 191, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        self.end_label.setFont(font)
        self.end_label.setObjectName("end_label")
        self.date_end = QtWidgets.QDateEdit(self.centralwidget)
        self.date_end.setGeometry(QtCore.QRect(560, 150, 161, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        self.date_end.setFont(font)
        self.date_end.setStyleSheet("background: rgb(242,242,242);")
        self.date_end.setCalendarPopup(True)
        self.date_end.setObjectName("date_end")
        self.date_begin = QtWidgets.QDateEdit(self.centralwidget)
        self.date_begin.setGeometry(QtCore.QRect(560, 90, 161, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        self.date_begin.setFont(font)
        self.date_begin.setStyleSheet("background: rgb(242,242,242);")
        self.date_begin.setCalendarPopup(True)
        self.date_begin.setObjectName("date_begin")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(850, 100, 91, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.code_text = QtWidgets.QTextEdit(self.centralwidget)
        self.code_text.setGeometry(QtCore.QRect(950, 90, 151, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        self.code_text.setFont(font)
        self.code_text.setStyleSheet("")
        self.code_text.setObjectName("code_text")
        self.okdp_text = QtWidgets.QTextEdit(self.centralwidget)
        self.okdp_text.setGeometry(QtCore.QRect(950, 150, 151, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        self.okdp_text.setFont(font)
        self.okdp_text.setObjectName("okdp_text")
        self.deya_text = QtWidgets.QTextEdit(self.centralwidget)
        self.deya_text.setGeometry(QtCore.QRect(950, 210, 151, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        self.deya_text.setFont(font)
        self.deya_text.setObjectName("deya_text")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(750, 160, 191, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(810, 220, 131, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.CreateRow = QtWidgets.QPushButton(self.centralwidget)
        self.CreateRow.setGeometry(QtCore.QRect(570, 270, 141, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        self.CreateRow.setFont(font)
        self.CreateRow.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.CreateRow.setAutoFillBackground(False)
        self.CreateRow.setStyleSheet("background-color: rgb(255, 204, 0);\n"
"border: 1px solid black;")
        self.CreateRow.setObjectName("CreateRow")
        self.comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox.setGeometry(QtCore.QRect(740, 270, 141, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        self.comboBox.setFont(font)
        self.comboBox.setStyleSheet("background-color: rgb(255, 204, 0);\n"
"border: 1px solid black;")
        self.comboBox.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContentsOnFirstShow)
        self.comboBox.setDuplicatesEnabled(False)
        self.comboBox.setFrame(True)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox_2 = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_2.setGeometry(QtCore.QRect(910, 270, 141, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        self.comboBox_2.setFont(font)
        self.comboBox_2.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.comboBox_2.setStyleSheet("background-color: rgb(255, 204, 0);\n"
"border: 1px solid black;")
        self.comboBox_2.setDuplicatesEnabled(False)
        self.comboBox_2.setFrame(True)
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget.setGeometry(QtCore.QRect(15, 381, 1083, 281))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.tableWidget.setFont(font)
        self.tableWidget.setStyleSheet("")
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(9)

        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(8, item)
        self.tableWidget.horizontalHeader().setVisible(True)
        self.tableWidget.horizontalHeader().setCascadingSectionResizes(False)
        self.tableWidget.horizontalHeader().setDefaultSectionSize(118)
        self.tableWidget.horizontalHeader().setHighlightSections(False)
        self.tableWidget.horizontalHeader().setMinimumSectionSize(40)
        self.tableWidget.verticalHeader().setVisible(True)
        self.tableWidget.verticalHeader().setCascadingSectionResizes(False)
        self.tableWidget.verticalHeader().setDefaultSectionSize(30)
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(38, 341, 233, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet("border: 1px solid black;\n"
"")
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(270, 341, 238, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        self.label_7.setFont(font)
        self.label_7.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_7.setStyleSheet("border: 1px solid black;\n"
"")
        self.label_7.setTextFormat(QtCore.Qt.AutoText)
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.label_of_period = QtWidgets.QLabel(self.centralwidget)
        self.label_of_period.setGeometry(QtCore.QRect(625, 341, 236, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        self.label_of_period.setFont(font)
        self.label_of_period.setStyleSheet("border: 1px solid black;\n"
"")
        self.label_of_period.setAlignment(QtCore.Qt.AlignCenter)
        self.label_of_period.setObjectName("label_of_period")
        self.label_of_period_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_of_period_2.setGeometry(QtCore.QRect(860, 341, 238, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        self.label_of_period_2.setFont(font)
        self.label_of_period_2.setStyleSheet("border: 1px solid black;\n"
"")
        self.label_of_period_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_of_period_2.setObjectName("label_of_period_2")
        self.who_text = QtWidgets.QTextEdit(self.centralwidget)
        self.who_text.setGeometry(QtCore.QRect(40, 210, 231, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        self.who_text.setFont(font)
        self.who_text.setStyleSheet("background: rgb(242,242,242);")
        self.who_text.setObjectName("who_text")
        self.work_text = QtWidgets.QTextEdit(self.centralwidget)
        self.work_text.setGeometry(QtCore.QRect(40, 270, 111, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        self.work_text.setFont(font)
        self.work_text.setStyleSheet("background: rgb(242,242,242);")
        self.work_text.setObjectName("work_text")
        self.tabel_text = QtWidgets.QTextEdit(self.centralwidget)
        self.tabel_text.setGeometry(QtCore.QRect(170, 270, 101, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        self.tabel_text.setFont(font)
        self.tabel_text.setStyleSheet("background: rgb(242,242,242);")
        self.tabel_text.setObjectName("tabel_text")
        self.org_label_2 = QtWidgets.QLabel(self.centralwidget)
        self.org_label_2.setGeometry(QtCore.QRect(40, 190, 241, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        self.org_label_2.setFont(font)
        self.org_label_2.setObjectName("org_label_2")
        self.org_label_3 = QtWidgets.QLabel(self.centralwidget)
        self.org_label_3.setGeometry(QtCore.QRect(40, 250, 111, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        self.org_label_3.setFont(font)
        self.org_label_3.setObjectName("org_label_3")
        self.org_label_4 = QtWidgets.QLabel(self.centralwidget)
        self.org_label_4.setGeometry(QtCore.QRect(170, 250, 211, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        self.org_label_4.setFont(font)
        self.org_label_4.setObjectName("org_label_4")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.CreateButton.setText(_translate("MainWindow", "Создать"))
        self.label.setText(_translate("MainWindow", "Отчет по таре: документ 1504-3002 от 16.04.2020 11:40:15"))
        self.org_label.setText(_translate("MainWindow", "Организация"))
        self.org_text.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Arial\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\';\"></span></p></body></html>"))
        self.podraz_text.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Arial\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\';\"></span></p></body></html>"))
        self.podraz_label.setText(_translate("MainWindow", "Подразделение"))
        self.data_create_label.setText(_translate("MainWindow", "Дата составления"))
        self.textEdit.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Arial\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt;\">1504-3002</span></p></body></html>"))
        self.label_2.setText(_translate("MainWindow", "Номер документа"))
        self.begin_label.setText(_translate("MainWindow", "Начало отчётного периода"))
        self.end_label.setText(_translate("MainWindow", "Конец отчётного периода"))
        self.label_3.setText(_translate("MainWindow", "Код по ОКПО"))
        self.code_text.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Arial\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'MS Shell Dlg 2\'; font-size:7.8pt;\"><br /></p></body></html>"))
        self.label_4.setText(_translate("MainWindow", "Вид деятельности по ОКДП"))
        self.label_5.setText(_translate("MainWindow", "Вид деятельности"))
        self.CreateRow.setText(_translate("MainWindow", "Добавить запись"))
        self.comboBox.setCurrentText(_translate("MainWindow", "Начало периода"))
        self.comboBox.setItemText(0, _translate("MainWindow", "Начало периода"))
        self.comboBox.setItemText(1, _translate("MainWindow", "Конец периода"))
        self.comboBox_2.setCurrentText(_translate("MainWindow", "Приход"))
        self.comboBox_2.setItemText(0, _translate("MainWindow", "Приход"))
        self.comboBox_2.setItemText(1, _translate("MainWindow", "Расход"))
        self.tableWidget.setSortingEnabled(False)

        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Наименование"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Код"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Наименование"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Код"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Цена"))
        item = self.tableWidget.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Количество"))
        item = self.tableWidget.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "Сумма"))
        item = self.tableWidget.horizontalHeaderItem(7)
        item.setText(_translate("MainWindow", "Количество"))
        item = self.tableWidget.horizontalHeaderItem(8)
        item.setText(_translate("MainWindow", "Сумма"))
        self.label_6.setText(_translate("MainWindow", "Тара"))
        self.label_7.setText(_translate("MainWindow", "Поставщик"))
        self.label_of_period.setText(_translate("MainWindow", "Начало периода"))
        self.label_of_period_2.setText(_translate("MainWindow", "Приход"))
        self.who_text.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Arial\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\';\"></span></p></body></html>"))
        self.work_text.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Arial\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"></p></body></html>"))
        self.tabel_text.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Arial\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\';\"></span></p></body></html>"))
        self.org_label_2.setText(_translate("MainWindow", "Материально ответственное лицо"))
        self.org_label_3.setText(_translate("MainWindow", "Должность"))
        self.org_label_4.setText(_translate("MainWindow", "Табельный номер"))
